name: Context Example
on: push

jobs:
  my-context-job:
    runs-on: ubuntu-latest
    steps:
     - name: "my step"
       run: echo "hello $MY_ACTION"
       env:
         MY_ACTION: ${{  github.action  }}
