name: Dep_jobs
on: push

jobs:

  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: echo "hello"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: step2
        run: echo "world"