name: "workflow commands"
on: push

jobs: 
  workflow_commands:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: |
          echo "::group:: My Group Message"
          echo "message1"
          echo "message2"
          echo "::endgroup::"
      - name: "add variable"
        run: echo "MY_VAL=JEFFERSON" >> GITHUB_ENV
      - name: "retreive variable"
        run: echo $MY_VAL