name: "workflow commands"

  on: push

  jobs: 
    workflow-commands:
      steps:
        - name: "group logging"
          run: |
            echo "::group:: My Group Message"
            echo "message1"
            echo "message2"
            echo "::endgroup::"
        - name: "add variable"
          run: echo "MY_VAL=JEFFERSON" >> GITHUB_ENV
        - name: "retreive variable"
          run: echo "$MY_VAL"